global_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 10.0
  publish_frequency: 5.0
  static_map: true
  inflation_radius: 0.01
  resolution: 0.01
  cost_scaling_factor:  100
  transform_tolerance: 0.5  
  #rolling_window: true
  #width: 5.5
  #height: 5.5
  #plugins:
   # - {name: static_layer,            type: "costmap_2d::StaticLayer"}
    #- {name: obstacle_layer,          type: "costmap_2d::VoxelLayer"}
    #- {name: inflation_layer,         type: "costmap_2d::InflationLayer"}
