local_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 10.0
  publish_frequency: 10.0
  static_map: false
  rolling_window: true
  width: 5.5
  height: 5.5
  resolution: 0.01
  transform_tolerance: 0.5
  cost_scaling_factor:  10.0
  inflation_radius: 0.01
  
  #plugins:
   #- {name: static_layer,        type: "costmap_2d::StaticLayer"}
   #- {name: obstacle_layer,      type: "costmap_2d::ObstacleLayer"}
